
AllCops:
  Exclude:
    - 'db/*'
    - 'config/*'
    - 'bin/*'
    - 'test/test_helper.rb'
    - 'config/initializers/devise.rb'


Metrics/LineLength:
  Enabled: true
  Max: 99

Layout/EndOfLine:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/EndOfLine:
  Enabled: false
