
AllCops:
  Exclude:
    - 'db/*'
    - 'config/*'
    - 'bin/*'
    - 'test/test_helper.rb'
    - 'test/controllers/*'
    - 'config/initializers/devise.rb'
    - 'app/channels/application_cable/*'
    - 'app/controllers/notifications/notifications_controller.rb'


Layout/EndOfLine:
  Enabled: true

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 15

Metrics/LineLength:
  Enabled: true
  Max: 99

Metrics/MethodLength:
  Enabled: true
  Max: 10

Style/BracesAroundHashParameters:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ClassMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/For:
  EnforcedStyle: for

Style/GuardClause:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: true

Style/NegatedIf:
  EnforcedStyle: postfix

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses
