default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  url: <%= ENV['DATABASE_URL'] %>


test:
  <<: *default
  database: myapp_test
